name: Test Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - gh_secrets_fix
jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      NTFY_URL: ${{ secrets.NTFY_URL }}
      NTFY_CREDS: ${{ secrets.NTFY_CREDS }}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run python
        run: |
          pip install requests && \
          python -c "import os, requests; requests.post(os.getenv('NTFY_URL'),headers={'Authorization': 'Bearer '+os.getenv('NTFY_CREDS')},data='Hello world')"
