name: Calculate Yields
on:
  workflow_dispatch:
jobs:
  test_job:
    runs-on: ubuntu-latest
    env:
      NTFY_CREDS: ${{ secrets.NTFY_CREDS }}
      NTFY_URL: ${{ secrets.NTFY_URL }}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run python
        run: |
          python -c "import os; print(os.getenv('NTFY_URL')[:-2])"
