name: Test ntfy
on:
  workflow_dispatch:
jobs:
  test_ntfy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Bypass Cloudflare for Github Actions
        uses: xiaotianxt/bypass-cloudflare-for-github-action@v2.1.0
        with:
          cf_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cf_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          cf_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          disable_bot_fight_mode: "true"
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Update packages
        run: sudo apt-get update
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller webdriver_manager selenium pyvirtualdisplay beautifulsoup4 lxml
      - name: Running the Python script
        env:
          NTFY_CREDS: ${{ secrets.NTFY_CREDS }}
          NTFY_URL: ${{ secrets.NTFY_URL }}
        run: python yield_comparison.py --ntfy
